//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOrderingSystem.registerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int ArtistID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Contact_No { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
    }
}
